pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'taskmanager'

[
    '1.20.1',
    '1.20.2',
    '1.20.3',
    '1.20.4',
    '1.20.5',
    '1.20.6',
    '1.21',
    '1.21.1',
    '1.21.2',
    '1.21.3',
    '1.21.4',
    '1.21.5',
    '1.21.6',
    '1.21.7',
    '1.21.8',
    '1.21.9',
    '1.21.10',
    '1.21.11'
].each { mcVersion ->
    def moduleName = "mc${mcVersion.replace('.', '_')}"
    def projectDirectory = file("versions/${mcVersion}")
    if (!projectDirectory.exists() && !projectDirectory.mkdirs()) {
        throw new GradleException("Failed to create project directory for ${moduleName}: ${projectDirectory}")
    }

    include(moduleName)
    project(":${moduleName}").projectDir = projectDirectory
}
